version: "3.8"
services:
  frontend:
    build: ./frontend
    image: kwame/award-project-frontend:latest
    container_name: award-project_frontend
    ports:
    - target: 5000
      published: 80
  backend: 
    build: ./backend
    image: kwame/award-project-backend:latest
    container_name: award-project_backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000
    
